<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.opensaml</groupId>
        <artifactId>opensaml-parent</artifactId>
        <version>4.3.2</version>
        <relativePath>../opensaml-parent</relativePath>
    </parent>

    <name>OpenSAML :: Core</name>
    <description>Core</description>
    <artifactId>opensaml-core</artifactId>
    <packaging>jar</packaging>

    <!-- Module properties and Java 1.8 compiler settings -->
    <properties>
        <automatic.module.name>org.opensaml.core</automatic.module.name>
        <maven.compiler.release>8</maven.compiler.release>
    </properties>

    <dependencies>
        <!-- Compile Dependencies -->
        <dependency>
            <groupId>commons-codec</groupId>
            <artifactId>commons-codec</artifactId>
        </dependency>

        <dependency>
        	<groupId>com.google.code.findbugs</groupId>
        	<artifactId>jsr305</artifactId>
        </dependency>

        <dependency>
        	<groupId>com.google.guava</groupId>
        	<artifactId>guava</artifactId>
        </dependency>

        <dependency>
            <groupId>io.dropwizard.metrics</groupId>
            <artifactId>metrics-core</artifactId>
        </dependency>

        <!-- Provided Dependencies -->

        <!-- Runtime Dependencies -->

        <!-- Test Dependencies -->

    </dependencies>
    
    <build>
        <plugins>
            <!-- Configure compiler plugin to explicitly use source/target 1.8 -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.14.0</version>
                <configuration>
                    <release>${maven.compiler.release}</release>
                </configuration>
                <!-- Skip compiling tests -->
                <executions>
                    <execution>
                    <id>default-testCompile</id>
                    <phase>test-compile</phase>
                    <goals>
                        <goal>testCompile</goal>
                    </goals>
                    <configuration>
                        <skip>true</skip>
                    </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <archive>
                        <index>true</index>
                        <manifestEntries>
                            <Main-Class>org.opensaml.core.Version</Main-Class>
                        </manifestEntries>
                        <manifestSections>
                            <manifestSection>
                                <name>org/opensaml/core/</name>
                                <manifestEntries>
                                    <Implementation-Title>${project.artifactId}</Implementation-Title>
                                    <Implementation-Version>${project.version}</Implementation-Version>
                                    <Implementation-Vendor>opensaml.org</Implementation-Vendor>
                                </manifestEntries>
                            </manifestSection>
                        </manifestSections>
                    </archive>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <scm>
        <connection>${shibboleth.scm.connection}java-opensaml</connection>
        <developerConnection>${shibboleth.scm.developerConnection}java-opensaml</developerConnection>
        <url>${shibboleth.scm.url}java-opensaml.git</url>
    </scm>

    <distributionManagement>
        <site>
            <id>site</id>
            <url>scp:${opensaml-module.site.url}</url>
        </site>
    </distributionManagement>

</project>
